const private_krankenkassen = [
  "Allianz Private Krankenversicherungs-AG",
  "ALTE OLDENBURGER Krankenversicherung AG",
  "ARAG Krankenversicherungs-AG",
  "AXA Krankenversicherung AG",
  "Barmenia Krankenversicherung AG",
  "Bayerische Beamtenkrankenkasse AG",
  "Concordia Krankenversicherungs-AG",
  "Continentale Krankenversicherung a.G.",
  "DBV Deutsche Beamtenversicherung Krankenversicherung AG",
  "Debeka Krankenversicherungsverein a.G.",
  "Deutscher Ring Krankenversicherungsverein a.G.",
  "DEVK Krankenversicherungs-AG",
  "DFV Deutsche Familienversicherung AG",
  "Die Bayerische",
  "DKV Deutsche Krankenversicherung AG",
  "ENVIVAS Krankenversicherung AG",
  "ERGO Direkt Krankenversicherung AG",
  "Freie Arzt- und Medizinkasse V.V.a.G.",
  "Generali Deutschland Krankenversicherung AG",
  "Gothaer Krankenversicherung AG",
  "HALLESCHE Krankenversicherung a.G.",
  "HanseMerkur Krankenversicherung AG",
  "HUK-COBURG-Krankenversicherung AG",
  "INTER Krankenversicherung AG",
  "Janitos Versicherung AG",
  "LIGA Krankenversicherung katholischer Priester V.V.a.G.",
  "LKH Landeskrankenhilfe V.V.a.G.",
  "LVM Krankenversicherungs-AG",
  "Mannheimer Krankenversicherung AG",
  "Mecklenburgische Krankenversicherungs-AG",
  "MÜNCHENER VEREIN Krankenversicherung a.G.",
  "NÜRNBERGER Krankenversicherung AG",
  "ottonova Krankenversicherung AG",
  "PAX-Familienfürsorge Krankenversicherung AG",
  "Provinzial Krankenversicherung Hannover AG",
  "R+V Krankenversicherung AG",
  "SDK Süddeutsche Krankenversicherung a.G.",
  "SIGNAL IDUNA Krankenversicherung a.G.",
  "St. Martinus Priesterverein V.V.a.G.",
  "UKV - Union Krankenversicherung AG",
  "uniVersa Krankenversicherung a.G.",
  "vigo Krankenversicherung V.V.a.G.",
  "WGV-Versicherung AG",
  "Württembergische Krankenversicherung AG",
];

const krankenkassen = [
  "AOK Baden-Württemberg",
  "AOK Bayern",
  "AOK Bremen/Bremerhaven",
  "AOK Hessen",
  "AOK Niedersachsen",
  "AOK Nordost",
  "AOK Nordwest",
  "AOK PLUS",
  "AOK Rheinland/Hamburg",
  "AOK Rheinland-Pfalz/Saarland",
  "AOK Sachsen-Anhalt",
  "Audi BKK",
  "BAHN-BKK",
  "BARMER",
  "BERGISCHE KRANKENKASSE",
  "Bertelsmann BKK",
  "BIG direkt gesund",
  "BKK Akzo Nobel Bayern",
  "BKK B. Braun Aesculap",
  "BKK Deutsche Bank AG",
  "BKK Diakonie",
  "BKK DürkoppAdler",
  "BKK EUREGIO",
  "BKK exklusiv",
  "BKK Faber-Castell & Partner",
  "BKK firmus",
  "BKK Freudenberg",
  "BKK GILDEMEISTER SEIDENSTICKER",
  "BKK Groz-Beckert",
  "BKK Herkules",
  "BKK Linde",
  "bkk melitta hmr",
  "BKK Miele",
  "BKK MTU",
  "BKK Pfalz",
  "BKK ProVita",
  "BKK Public",
  "BKK SBH",
  "BKK Scheufelen",
  "BKK Technoform",
  "BKK VDN",
  "BKK VerbundPlus",
  "BKK Werra-Meissner",
  "BKK Wirtschaft & Finanzen",
  "BKK ZF & Partner",
  "BKK24",
  "Bosch BKK",
  "Continentale BKK",
  "DAK-Gesundheit",
  "Debeka BKK",
  "energie-BKK",
  "Heimat Krankenkasse",
  "HEK - Hanseatische Krankenkasse",
  "IKK - Die Innovationskasse",
  "IKK Brandenburg und Berlin",
  "IKK classic",
  "IKK gesund plus",
  "IKK Südwest",
  "Kaufmännische Krankenkasse - KKH",
  "KNAPPSCHAFT",
  "mhplus Krankenkasse",
  "Mobil Krankenkasse",
  "Novitas BKK",
  "pronova BKK",
  "R+V Betriebskrankenkasse",
  "Salus BKK",
  "SECURVITA Krankenkasse",
  "Siemens-Betriebskrankenkasse (SBK)",
  "SKD BKK",
  "Techniker Krankenkasse (TK)",
  "TUI BKK",
  "VIACTIV Krankenkasse",
  "vivida bkk",
  "WMF BKK",
];

module.exports = {
  private_krankenkassen,
  krankenkassen,
};
